import { Inter } from "next/font/google";
import Header from "@/components/Header";
import Slider from "react-slick";
import ProductDetail from "@/components/ProductDetail";
import ProductList from "@/components/ProductList";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}

        <Header />
        <Slider />
        <ProductList />
        <ProductDetail />
        {children}
      </body>
    </html>
  );
}
